#!/bin/sh -e

clean()
{
    rm -rfv $1/.*~
    rm -rfv $1/*~
    rm -rfv $1/*.default
    rm -rfv $1/*.sample
}

if [ $1 ]
then
    if [ -d $1 ]
    then
	clean $1
    else
	echo "$1 not a directory"
    fi
else
    clean `pwd`
fi
